"""Add model_id to generated_images

Revision ID: ad2442261c10
Revises: 392f4a4e34f2
Create Date: 2025-07-02 00:05:34.266742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad2442261c10'
down_revision: Union[str, Sequence[str], None] = '392f4a4e34f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_images', sa.Column('model_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'generated_images', 'models', ['model_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'generated_images', type_='foreignkey')
    op.drop_column('generated_images', 'model_id')
    # ### end Alembic commands ###
