"""Add token tracking fields to User and TokenHistory models

Revision ID: 2782592d4ab6
Revises: 78ae6938eb0b
Create Date: 2025-09-04 13:34:25.238606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2782592d4ab6'
down_revision: Union[str, Sequence[str], None] = '78ae6938eb0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('change', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('validity_extension', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('token_balance', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('token_valid_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_valid_until')
    op.drop_column('users', 'token_balance')
    op.drop_table('token_history')
    # ### end Alembic commands ###
