"""add description column to tasks

Revision ID: 552b9f9624c2
Revises: 88c090d7235f
Create Date: 2025-07-15 14:35:23.488044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '552b9f9624c2'
down_revision: Union[str, Sequence[str], None] = '88c090d7235f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('description', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('pose', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'pose')
    op.drop_column('tasks', 'description')
    # ### end Alembic commands ###
