"""Add GarmentImage model and update relationships

Revision ID: 78ae6938eb0b
Revises: 552b9f9624c2
Create Date: 2025-07-15 17:03:44.526618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78ae6938eb0b'
down_revision: Union[str, Sequence[str], None] = '552b9f9624c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('garment_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_garment_images_id'), 'garment_images', ['id'], unique=False)
    op.drop_column('batches', 'garment_image_url')
    op.add_column('generated_images', sa.Column('garment_image_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('generated_images_batch_id_fkey'), 'generated_images', type_='foreignkey')
    op.create_foreign_key(None, 'generated_images', 'garment_images', ['garment_image_id'], ['id'])
    op.drop_column('generated_images', 'batch_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_images', sa.Column('batch_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'generated_images', type_='foreignkey')
    op.create_foreign_key(op.f('generated_images_batch_id_fkey'), 'generated_images', 'batches', ['batch_id'], ['id'])
    op.drop_column('generated_images', 'garment_image_id')
    op.add_column('batches', sa.Column('garment_image_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_garment_images_id'), table_name='garment_images')
    op.drop_table('garment_images')
    # ### end Alembic commands ###
